<?php
/**
 * Weather Polls API
 * Returns polls triggered by current weather conditions
 */

header('Content-Type: application/json');
require_once 'includes/bootstrap.php';
require_once 'includes/WeatherService.php';
require_once 'includes/Models/WeatherTrigger.php';
require_once 'includes/Models/Poll.php';

try {
    $weatherService = new WeatherService($db);
    $weatherTrigger = new WeatherTrigger($db);
    
    // Get location from query parameter or auto-detect
    $location = $_GET['location'] ?? 'auto';
    
    // Get current weather
    $weather = $weatherService->getCurrentWeather($location);
    
    if (!$weather) {
        throw new Exception('Unable to fetch weather data');
    }
    
    // Auto-generate polls based on weather (max 3)
    $autoGenerated = $weatherTrigger->autoGeneratePolls($weather, 3);
    
    // Get all active weather-triggered polls
    $activePolls = $weatherTrigger->getActiveWeatherPolls();
    
    // Get poll results for each poll
    $pollModel = new Poll($db);
    foreach ($activePolls as &$poll) {
        $results = $pollModel->getResults($poll['poll_id']);
        $poll['results'] = $results;
    }
    
    // Clean up expired polls
    $weatherTrigger->cleanupExpiredPolls();
    
    echo json_encode([
        'success' => true,
        'weather' => [
            'condition' => $weather['condition'],
            'description' => $weather['description'],
            'temperature' => $weather['temperature'],
            'feels_like' => $weather['feels_like'],
            'location' => $weather['location'],
            'icon' => $weather['icon'],
            'icon_url' => $weatherService->getIconUrl($weather['icon']),
            'is_mock' => $weather['is_mock'] ?? false
        ],
        'polls' => $activePolls,
        'auto_generated' => count($autoGenerated),
        'timestamp' => date('Y-m-d H:i:s')
    ]);
    
} catch (Exception $e) {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'error' => $e->getMessage()
    ]);
}
